language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

notifications:
  email:
    on_failure: change # [always|never|change] default: always

install:
  - pip install git+git://github.com/ioam/param.git
  - pip install git+git://github.com/ioam/dataviews.git
  - pip install jinja2 tornado pyzmq matplotlib pillow
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install ipython==1.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install ipython; fi

before-script:
  - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - nosetests --with-doctest